language: python
cache: pip
python:
  - 3.6
install:
  # pandocfilters needed for nbconvert and nbsphinx
  - pip install codecov pandocfilters tox-travis
script:
  - tox
after_success:
  - codecov
notifications:
  email: false